spring.application.name=demo

god.api.greek-url=https://my-json-server.typicode.com/jabrena/latency-problems/greek
god.api.roman-url=https://my-json-server.typicode.com/jabrena/latency-problems/roman
god.api.nordic-url=https://my-json-server.typicode.com/jabrena/latency-problems/nordic
god.api.timeout-seconds=5
